# {{SERVICE_NAME}} - {{DESCRIPTION}}
# Generated by GX Genesis | Team: {{TEAM}} | Tier: {{TIER}} | Eco: {{ECO_NAME}}

# Build stage
FROM node:18-alpine AS builder

# Set working directory
WORKDIR /app

# Copy package files for better Docker layer caching
COPY package*.json ./
COPY yarn.lock* ./

# Install ALL dependencies (including devDependencies) for building
RUN npm install && npm cache clean --force

# Copy application code
COPY src ./src
COPY public ./public
COPY next.config.js ./
COPY tsconfig.json ./
COPY tailwind.config.js ./
COPY postcss.config.js ./
COPY next-env.d.ts ./

# Build the Next.js application
RUN npm run build

# Production stage
FROM node:18-alpine AS runner

# Labels for Galaxy platform
LABEL service.name="{{SERVICE_NAME}}" \
      service.tier="{{TIER}}" \
      service.workload="{{TIER}}" \
      service.team="{{TEAM}}" \
      service.eco="{{ECO_NAME}}" \
      galaxy.io/managed-by="galaxy"

# Create non-root user for security
RUN addgroup -g 1001 -S nodejs
RUN adduser -S nextjs -u 1001

# Set working directory
WORKDIR /app

# Copy package files and install production dependencies only
COPY package*.json ./
RUN npm install --only=production && npm cache clean --force

# Copy built application from builder stage
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
COPY --from=builder --chown=nextjs:nodejs /app/public ./public

# Switch to non-root user
USER nextjs

# Expose port from tier configuration
EXPOSE {{TIER_CONFIG.port}}

# Galaxy health check with service metadata
HEALTHCHECK --interval=30s --timeout=10s --start-period=5s --retries=3 \
    CMD curl -f -H "X-Service-Name: {{SERVICE_NAME}}" -H "X-Service-Team: {{TEAM}}" -H "X-Service-Tier: {{TIER}}" -H "X-Service-Eco: {{ECO_NAME}}" -H "X-Galaxy-Managed: true" http://127.0.0.1:{{TIER_CONFIG.port}}/health || exit 1

# Start the Galaxy UI service
CMD ["node", "server.js"]
